import MainLayout from "../components/layouts/MainLayout";
import HomeBanner from "../components/home/Banner";
import Head from "next/head";
import { Roboto } from "@next/font/google";
import {
  BASE_API,
  CombineType,
  KEY_API,
  NextPageWithLayout,
  REVALIDATE_TIME,
} from "../common/common";
import { Movie } from "../common/movie";
import "swiper/css";
import dynamic from "next/dynamic";

const TopRate = dynamic(() => import("../components/home/TopRate"));
const TopTv = dynamic(() => import("../components/home/TopTv"));
const RecommendToday = dynamic(
  () => import("../components/home/RecommendToday")
);

const roboto = Roboto({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "700"],
});
interface HomePageProps {
  topMovies: CombineType[];
}
const HomePage: NextPageWithLayout<HomePageProps> = ({ topMovies }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Trang chủ</title>
      </Head>
      <main className={roboto.className}>
        <HomeBanner />
        {topMovies && <TopRate listMovies={topMovies} />}
        <RecommendToday />
        <TopTv />
      </main>
    </>
  );
};

export async function getStaticProps() {
  const res = await fetch(`${BASE_API}/movie/top_rated?api_key=${KEY_API}`);
  const { results } = await res.json();
  const topMovies: Movie[] = results;
  return {
    props: {
      topMovies: topMovies.slice(0, 16).map((movie) => ({
        id: movie.id,
        poster_path: movie.poster_path,
        release_date: movie.release_date,
        title: movie.title,
        vote_average: movie.vote_average,
      })),
    },
    revalidate: REVALIDATE_TIME, // In seconds
  };
}

HomePage.getLayout = (page) => <MainLayout>{page}</MainLayout>;
export default HomePage;
