import Head from "next/head";
import { Roboto } from "@next/font/google";
import HomeBanner from "../components/home/Banner";
import MainLayout from "../components/layouts/MainLayout";
import { NextPageWithLayout } from "../common/common";

const roboto = Roboto({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "700"],
});
const HomePage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Trang chủ</title>
      </Head>
      <main className={roboto.className}>
        <HomeBanner />
      </main>
    </>
  );
};
HomePage.Layout = MainLayout;
export default HomePage;
